---
title: "Análisis de las poblaciones de *Quiscalus Mexicanus* y *Ortalis Garrula* en el área urbana y distrital de Barranquilla entre 2015-2025"
author: "Nelson Pulecio"
date: "last-modified"
toc: true 
format:
  html:
    theme: journal
    embed-resources: true
    css: estilos.css #esto justifica todo el texto para renderizado en HTML
editor: visual
lang: es
code-fold: true
bibliography: referencias.bib #archivo de referencias desde zotero
---

## Introducción

La *Quiscalus mexicanus* comúnmente llamada Maria Mulata figura como una de las especies más representativas de la ciudad de Barranquilla, Atlántico, de tal forma que hace parte de la matriz del paisaje urbano. Morfologicamente la *Quiscalus mexicanus* destaca por un plumaje brillante de tonalidad oscura para los machos y para las hembras una tonalidad marrón y con plumas de tonalidad clara en las cejas y vientre, a diferencia de otras especies como *Quiscalus lugubris* la cual es significativamente más pequeña y con una cola más corta. Aunque no existe un consenso de cuando ni como se dio la introducción de *Quiscalus mexicanus* al departamento del atlántico, @dugandHttpWwwjstororgAVES1947 resalta que existen registros en la ciudad de Barranquilla al menos desde 1895. Dugand la describe como una especie con preferencia por los cuerpos de agua como Boca de Cenizas, Salgar o Puerto Colombia, también resalta su alta frecuencia en las poblaciones, en barrios como el Prado y la zona mercantil de Barranquilla, donde bajaba a comer los desperdicios de las cocinas.

Este aparente comportamiento oportunista y alta capacidad de adaptación al entorno urbano y rural al día de hoy tiene soporte en diversos estudios relacionados a su alimentación. En México, por ejemplo, se ha reportado una gran variedad de alimentos como cangrejos de la especie *Uca beebei*, granos, frutas, geckos, renacuajos de anuro, neonatos de tortuga marina de la especie *Lepidochelys olivacea*, golondrinas de la especie *Hirundo rustica* e incluso se reporta alimentación por parte de los insectos muertos adheridos a las matriculas de los autos, alimentos industrializados y comportamientos como forrajeo de bolsas de basura. [@cupul-maganaObservacionesGeneralesDieta2018; @gurrolahidalgoDosNuevosRegistros2009; @cannNOTASCAMPOFIELD2022]

Por otro lado, la *Ortalis garrula*, cuyo nombre común es guacharaca, fue clasificada por primera vez por Humboldt en 1805 [@OLIVARES_1966] y se considera uno de los símbolos representativos de la región caribe al ser una especie endémica colombiana (solo tiene distribución en Colombia) cuyas poblaciones están mayormente centradas en la región caribe, aunque también tiene distribución en la región andina y reducidas poblaciones en la región pacifico. [@ChestnutwingedChachalacaEBird] a nivel morfológico *Ortalis garrula* es un ave de tamaño mediano la cual no tiene dimorfismo sexual (machos y hembras son morfologicamente iguales) y se caracteriza por un plumaje de tonos marrones en el lomo, tonos rojizos bajo el pico y las alas así como tonos blanquecinos en el vientre y las patas.

Actualmente *Ortalis garrula* es considerada una especie sombrilla para la región caribe, lo que quiere decir que el cuidado de las poblaciones de esta ave y su habitad implica un cuidado de diversas especies y ecosistemas asociados a ella. Respecto a su alimentación, @setina3ARTICULOSNOTAS2012 resalta que su dieta se compone de los frutos de *Brosimum utile, Eugenia oblongifolia, Ficus sp., Miconia sp., Psychotria sp., y Bellusia sp.* junto con el consumo de insectos, alimentación relacionada a su preferencia por bosques primarios y secundarios a diferencias de zonas en recuperación o cultivos agrícolas.
Aunque *Ortalis garrula* está clasificada como LC, es decir, preocupación menor por la UICN [@IUCNRedList] se considera según los criterios de la AICAS (Áreas importantes para la conservación de las aves y la biodiversidad) como una especie de distribución restringida. 
